# Sesi 4 Numpy Introduction

## Array

In [1]:
import numpy as np

a = np.array([1, 2, 3])

In [2]:
a

array([1, 2, 3])

In [3]:
# Pembuatan array yang isinya 0

np.zeros(3)

array([0., 0., 0.])

In [4]:
# Atau array dengan isi 1

np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# Atau juga array yang kosong
# Dan akan terisi random tergantung state memory

np.empty(7)

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 7.13443431e+91])

In [6]:
# Pembuatan array dengan range elemen

print(np.arange(4))
print(np.arange(0,12,3))

[0 1 2 3]
[0 3 6 9]


## Add, Remove dan Sort

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.append(arr, [4,5])

array([1, 2, 3, 4, 5, 6, 7, 8, 4, 5])

In [9]:
np.delete(arr, 7)

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
arr = np.array([2, 1, 9, 7, 5 , 3, 4, 8, 6])

In [11]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Shape and Size

In [30]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [20]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [32]:
# Bisa menabmahkan axis baru dengan np.newaxis

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [33]:
# Dapat mengkonversi array menjadi row vector

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [34]:
# Dan juga menjadi col vector

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [36]:
# Dapat menggunakan np.expand_dims untuk menambahkan axis pada index tertentu, contoh pada index 1

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [37]:
# untuk menambahkan axis pada posisi 0

b = np.expand_dims(a, axis=0)
b.shape

(1, 6)

## Indexing and Slicing

In [38]:
data = np.array([1, 2, 3])

print(data)
print(data[1])
print(data[2])
print(data[0:2])
print(data[-2:])
print(data[1:])

[1 2 3]
2
3
[1 2]
[2 3]
[2 3]


In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# Dapat mengeprint sesuai kemauan value nya contoh yang dibawah 5 saja

print(a[a<5])

[1 2 3 4]


In [42]:
# Bisa juga dengan cara:

five_up = (a >= 5)
print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [44]:
# Dapat memilih angka2 yang dapat dibagi 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [46]:
# Bisa juga memilih elemen yang terpenuhi dalam 2 syarat

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [48]:
arr1 = arr[3:9]
arr1

array([4, 5, 6, 7, 8, 9])

In [49]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [50]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [52]:
# Digabung secara vertical

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [54]:
# Digabung secara horizontal

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [58]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                     [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [56]:
# Jika mau di split menjadi array yang sama jumlahnya

np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]), array([[ 4,  5,  6],
        [16, 17, 18]]), array([[ 7,  8,  9],
        [19, 20, 21]]), array([[10, 11, 12],
        [22, 23, 24]])]

In [59]:
np.vsplit(arrsplit,2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [60]:
np.hsplit(arrsplit,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]), array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [61]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [62]:
# Dapat ditampilkan sesuai datanya

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
# Dapat dicopy datanya dan tidak akan berubah lagi jika a nya diubah2

b = a.copy()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [65]:
a = np.array([1,2,3,4])

# Ditambahkan elemen dalam arraynya
a.sum()

10

In [66]:
# Untuk 2D array harus dijelaskan axisnya

b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [67]:
# Jika mau ditambahkan secara row nya

b.sum(axis=0)

array([3, 3])

In [68]:
# Jika mau ditambahkan secara column nya

b.sum(axis=1)

array([2, 4])

In [69]:
data = np.array([1, 2])
data

array([1, 2])

In [70]:
ones = np.ones(2)
ones

array([1., 1.])

In [71]:
data + ones

array([2., 3.])

In [72]:
data * data

array([1, 4])

In [73]:
data / data

array([1., 1.])

## Broadcasting

In [75]:
data = np.array([1, 2])
data

array([1, 2])

In [76]:
data * 2.4

array([2.4, 4.8])

## More Array Operations

In [78]:
A = np.array([[1.43, 0.28],
              [0.96, 0.22],
              [2.21, 0.12]])
A

array([[1.43, 0.28],
       [0.96, 0.22],
       [2.21, 0.12]])

In [79]:
A.sum()

5.22

In [80]:
A.min()

0.12

In [81]:
A.min(axis=0)

array([0.96, 0.12])

In [82]:
A.min(axis=1)

array([0.28, 0.22, 0.12])

In [85]:
A.std() # Untuk standar deviasi

0.7583315018292901

In [86]:
A.max()

2.21

## Creating Matrices

In [92]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [98]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [99]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [95]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [102]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Dot Product

In [103]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [104]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [109]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


## Matrix Aggregation

In [110]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [111]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [149]:
print(data.max(axis=0))          # axis 0 sama dengan baris, axis 1 sama dengan y kolom
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [113]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [114]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [116]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [117]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [121]:
ndarr = np.array([[[1,2], [3,4]],
                 [[5,6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flatten N-Dimensional Array

In [122]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
arrflat.flatten()      # Untuk membuat array nya jadi flat 1 dimensi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [137]:
# Bisa membuat rumus dengan menggunakan bantuan NumPy

## Notes on Numpy Vector

In [127]:
a = np.random.rand(5)

In [128]:
print(a)

[0.94593184 0.08249438 0.40567659 0.18808217 0.09873095]


In [129]:
a.shape # Rank 1 Array

(5,)

In [130]:
print(a.T)

[0.94593184 0.08249438 0.40567659 0.18808217 0.09873095]


In [131]:
print(np.dot(a, a.T))

1.1112885576197522


In [147]:
a = np.random.rand(5, 1) # Column Vector, urutannya selalu (baris,kolom)
print(a)

[[0.59489776]
 [0.78060326]
 [0.68465355]
 [0.22788794]
 [0.3146412 ]]


In [134]:
print(a.T)

[[0.4727362  0.16064092 0.0662439  0.78135201 0.99235966]]


In [136]:
print(np.dot(a, a.T))

[[0.90890509 0.94363432 0.2793507  0.78844699 0.11592828]
 [0.94363432 0.97969055 0.29002468 0.81857352 0.1203579 ]
 [0.2793507  0.29002468 0.08585805 0.24232808 0.0356304 ]
 [0.78844699 0.81857352 0.24232808 0.68395333 0.10056419]
 [0.11592828 0.1203579  0.0356304  0.10056419 0.01478633]]


In [146]:
a = np.random.rand(1, 5) # row vector, urutannya selalu (baris,kolom)

In [140]:
print(a)

[[0.04448473 0.77340948 0.79603515 0.72689545 0.55940584]]


Don't use rank 1 Array; Always use 1 by n matrices or n by 1 matrices instead. (column or row vectors)

In [141]:
# Contoh pengaplikasian matrix multiplikasi

# Apel harga 3, Cherry harga 4, blueberry harga 2

# Apel terjual pada hari senin - kamis, 13;9;7;15
# Cherry terjual pada hari senin - kamis, 8;7;4;6
# Blueberry terjual pada hari senin - kamis 6;4;0;3

In [142]:
a = np.array([[3,4,2]])
a

array([[3, 4, 2]])

In [143]:
b = np.array([[13,9,7,15], [8,7,4,6], [6,4,0,3]])
b

array([[13,  9,  7, 15],
       [ 8,  7,  4,  6],
       [ 6,  4,  0,  3]])

In [145]:
np.dot(a, b) # Dapat mengetahui jumlah pemasukan perhari nya (senin - kamis)

array([[83, 63, 37, 75]])

In [148]:
np.mean(b, axis=0)

array([9.        , 6.66666667, 3.66666667, 8.        ])

In [150]:
np.mean(b, axis=1)

array([11.  ,  6.25,  3.25])

In [151]:
a = np.array([[1, 2, 3, 4, 5, 6, 7]])
print(a)

[[1 2 3 4 5 6 7]]


In [152]:
np.save("h8", a)

In [153]:
b = np.load("h8.npy")

In [154]:
print(b)

[[1 2 3 4 5 6 7]]


In [155]:
arr2D = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])

In [159]:
np.savetxt("h8.csv", arr2D)

In [161]:
np.loadtxt("h8.csv")

array([[11., 12., 13., 14.],
       [15., 16., 17., 18.],
       [19., 20., 21., 22.]])